### ISSUE TITLE
Profile picture size is not consistant 

### ISSUE THREAD

**Issue by guitarlass** [AmilaEranda/innovation_dashboard#12]
Please check below screen shots;
![1](https://cloud.githubusercontent.com/assets/7930964/6801496/3997c3dc-d24e-11e4-84b1-ab5a1c4bd8eb.PNG)
![2](https://cloud.githubusercontent.com/assets/7930964/6801497/39a36dcc-d24e-11e4-8223-8a15daffb16f.PNG)
![3](https://cloud.githubusercontent.com/assets/7930964/6801498/39a9c406-d24e-11e4-9289-4899a8c7bdd3.PNG)

**Comment by AmilaEranda** [comment]
Hi,
In profile picture upload section we mention that for best results upload a square image.
![1](https://cloud.githubusercontent.com/assets/1001547/6818703/e1abc906-d2da-11e4-93fb-fbc74139233f.JPG)
![2](https://cloud.githubusercontent.com/assets/1001547/6818704/e1b08b3a-d2da-11e4-922c-0870d1bcdf2b.JPG)
![3](https://cloud.githubusercontent.com/assets/1001547/6818705/e1c88104-d2da-11e4-8ee3-435e92a50e10.JPG)
![4](https://cloud.githubusercontent.com/assets/1001547/6818753/e21023dc-d2db-11e4-9ebe-875370c85791.JPG)
