### ISSUE TITLE
Organization list - duplicates

### ISSUE THREAD

**Issue by guitarlass** [AmilaEranda/innovation_dashboard#4]
I have informed about this earlier too. But today it happened again. Just after i finished adding a new organization to the list, it shows duplicates as shown in the screen shot. This is a rare occurrence.
![1](https://cloud.githubusercontent.com/assets/7930964/6226860/77550a86-b6bf-11e4-92f7-ea87953efefe.PNG)

**Comment by AmilaEranda** [comment]
Can you please send me the email of user.

**Comment by AmilaEranda** [comment]
Hi I checked user logs and find the person.And I compare the particular user with previous database backups.I found that there are duplicate records for that person.What are the changes you directly do to the database?

**Comment by guitarlass** [comment]
I don't think you found the user i refered to. This happened when i was editing organization details of person ID 1378. As i have explained this issue previously, its not happening because there are duplicate records in the database. because when i refreshed the page, duplicate records are no longer there.. you probably refer to a user with a duplicates. Still i'm not done with clearing duplicates. 
issue might be with the plugging you are using...

**Comment by AmilaEranda** [comment]
I found the user you refered using user logs in database.Organization details page updated.Now page automatically refresh after edit,save or delete.So error will not occur again.In my point of view this can happen because appropriate java script files not loaded properly.

**Comment by guitarlass** [comment]
Thank you. It's working.
