### ISSUE TITLE
Civil status as -1

### ISSUE THREAD

**Issue by guitarlass** [AmilaEranda/innovation_dashboard#5]
is this normal? only edited records are having civil status as -1
![capture](https://cloud.githubusercontent.com/assets/7930964/6244386/fb2bb936-b778-11e4-9a3e-584ccbee78a3.PNG)

**Comment by AmilaEranda** [comment]
Yes this is normal.When registering a new user, we are not asking his/her civil status.If he/she modify basic details,then this field add automatically. -1 means person doesn't provide gender details.

**Comment by guitarlass** [comment]
Thanks for the feedback
