### ISSUE TITLE
Error messages and Alters of the system

### ISSUE THREAD

**Issue by guitarlass** [AmilaEranda/innovation_dashboard#6]
Following is the error message i got because i inserted a long number to the telephone number field 
"Error while updating contact details.Please contact support team.Thank you."
We need to use relevant error messages for each error in the system. For example, for the above scenario you can alert the user "Maximum length of the telephone number should not be more than 10 digits"
I would like to suggest doing this using client side validation before submitting the form. If you could display the error next to the field that's better (while user is typing in). 
Data type should also be tested to restrict user from entering irrelevant data. For example, for the telephone field, if user entered characters to the filed: "telephone should only contain numbers". 

Another thing, please change the position of the alters and errors of the system appropriately. Most of the alters are appearing on very bottom of the page and i often have to scowl down to read it. 
![error](https://cloud.githubusercontent.com/assets/7930964/6245667/ec7c3150-b786-11e4-86c3-d0493b72689d.PNG)

**Comment by AmilaEranda** [comment]
Contact details page 
Message box problem solved in contact details page. When entering telephone numbers,we are restricting length now.We can't exactly says that,  "telephone should only contain numbers" because, some cases people input some symbols such as +, (, ) . Is there any use case, need to enter long number in to telephone number field as you said?What is the length of number you entered?

**Comment by guitarlass** [comment]
Thanks, I think 22 characters

**Comment by AmilaEranda** [comment]
Now we restrict it to 20 characters from front end.

**Comment by guitarlass** [comment]
Thanks, What about the positions of the messages?

**Comment by AmilaEranda** [comment]
It's already fixed.Is there any new message boxes which are not display properly?

**Comment by guitarlass** [comment]
Prefer it at the middle. Thanks.
![msgbox](https://cloud.githubusercontent.com/assets/7930964/6324077/80a176c0-bb5a-11e4-9db2-ca7715ed64c7.PNG)
