### ISSUE TITLE
Editing Organization detail

### ISSUE THREAD

**Issue by guitarlass** [AmilaEranda/innovation_dashboard#8]
Hi,
1. When setting a institution as the last institution (edit form), it automatically sets that same institution as the current institution.
2. Please change text labels of the organization editing form to: "Current university/ institution", "Last university/ institution"

**Comment by AmilaEranda** [comment]
Hi,
1. Yes last university should be set as his current university, because researcher should map to an university. We discussed about this before.
2. Labels changed as request.
