### ISSUE TITLE
Uploading publications

### ISSUE THREAD

**Issue by guitarlass** [AmilaEranda/innovation_dashboard#9]
The upload feature of publication form should only accept PDFs. Please do that validation.
Next, we tried to upload a publication without entering other details of the form. Then it popsup an error message saying the name of the file contains invalid characters. 
Please look into this issue.
Thanks.

**Comment by AmilaEranda** [comment]
1. Some people have various type of files.We can't restrict user should upload pdf files only.If you want we can restrict that.
2. " file contains invalid characters" means you are trying to upload a file with invalid file name.We are validating file name before upload.There are no relation between other details and this message.

**Comment by guitarlass** [comment]
We will re-check the functionality. thanks
